<?php

namespace Database\Seeders;

use App\Enums\CompanyReviewStatus;
use App\Enums\InvoiceStatus;
use App\Models\Company;
use App\Models\CompanyAddress;
use App\Models\CompanyCategory;
use App\Models\Invoice;
use App\Models\Plan;
use App\Models\State;
use App\Models\User;
use App\Services\CompanyPublicationService;
use CyrildeWit\EloquentViewable\View;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * Dev-only demo data for showcasing the dashboard/company-views screens.
 * Not called from DatabaseSeeder — run explicitly with
 * `php artisan db:seed --class=DemoDataSeeder`.
 *
 * Deliberately does not use WithoutModelEvents: subscription slugs
 * (spatie/laravel-sluggable) and media conversions are generated by model
 * event listeners, so this seeder needs them to fire.
 */
class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        if (app()->environment('production')) {
            $this->command?->error('DemoDataSeeder must not be run in production.');

            return;
        }

        if (CompanyCategory::query()->doesntExist()) {
            $this->call(CompanyCategorySeeder::class);
        }

        if (State::query()->doesntExist()) {
            $this->call(CountrySeeder::class);
            $this->call(StateSeeder::class);
        }

        if (Plan::query()->doesntExist()) {
            $this->call(PlanSeeder::class);
        }

        $user = User::updateOrCreate(
            ['email' => 'demo@viravach.com'],
            [
                'name' => ['en' => 'Demo', 'fa' => 'دمو'],
                'family' => ['en' => 'User', 'fa' => 'کاربر'],
                'phone' => '09120000000',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
            ],
        );

        $categories = CompanyCategory::inRandomOrder()->limit(10)->get();
        $states = State::inRandomOrder()->limit(10)->get();

        $companyConfigs = [
            ['plan_slug' => null, 'review_status' => CompanyReviewStatus::Approved],
            ['plan_slug' => 'pro-3-months', 'review_status' => CompanyReviewStatus::Approved],
            ['plan_slug' => 'pro-plus-6-months', 'review_status' => CompanyReviewStatus::Approved],
            ['plan_slug' => 'pro-1-year', 'review_status' => CompanyReviewStatus::Approved, 'expired' => true],
            ['plan_slug' => null, 'review_status' => CompanyReviewStatus::PendingReview],
        ];

        foreach ($companyConfigs as $config) {
            $isApproved = $config['review_status'] === CompanyReviewStatus::Approved;

            $company = Company::factory()->for($user)->create([
                'review_status' => $config['review_status'],
                'reviewed_at' => $isApproved ? now()->subDays(random_int(5, 60)) : null,
                'is_verified' => $isApproved,
            ]);

            if ($categories->isNotEmpty()) {
                $company->categories()->attach(
                    $categories->random(min(2, $categories->count()))->pluck('id'),
                );
            }

            if ($states->isNotEmpty()) {
                $state = $states->random();

                CompanyAddress::factory()->for($company)->create([
                    'country_id' => $state->country_id,
                    'state_id' => $state->id,
                    'is_primary' => true,
                ]);
            }

            // Approved companies get a public snapshot, and public views are
            // recorded against that snapshot.
            if ($isApproved) {
                app(CompanyPublicationService::class)->publish($company);
                $this->seedViewsForCompany($company);
            }

            $this->assignPlan($company, $config);
            $this->seedInvoicesForCompany($user, $company);
        }
    }

    /**
     * @param  array{plan_slug: ?string, review_status: CompanyReviewStatus, expired?: bool}  $config
     */
    private function assignPlan(Company $company, array $config): void
    {
        if ($config['plan_slug'] === null) {
            return;
        }

        $plan = Plan::where('slug', $config['plan_slug'])->first();

        if (! $plan) {
            return;
        }

        $subscription = $company->newPlanSubscription('main', $plan);

        if (! empty($config['expired'])) {
            $subscription->forceFill([
                'starts_at' => now()->subYear(),
                'ends_at' => now()->subDays(10),
                'trial_ends_at' => null,
            ])->save();
        }
    }

    private function seedViewsForCompany(Company $company): void
    {
        $publication = $company->publication;

        if ($publication === null) {
            return;
        }

        $rows = [];

        foreach (range(0, 29) as $daysAgo) {
            $viewsToday = random_int(0, 12);

            for ($i = 0; $i < $viewsToday; $i++) {
                $rows[] = [
                    'viewable_type' => $publication::class,
                    'viewable_id' => $publication->id,
                    'visitor' => Str::uuid()->toString(),
                    'collection' => null,
                    'viewed_at' => now()->subDays($daysAgo)->subMinutes(random_int(0, 1439))->format('Y-m-d H:i:s'),
                ];
            }
        }

        if ($rows !== []) {
            View::query()->insert($rows);
        }
    }

    private function seedInvoicesForCompany(User $user, Company $company): void
    {
        foreach ([InvoiceStatus::Paid, InvoiceStatus::Paid, InvoiceStatus::Pending] as $status) {
            Invoice::factory()->for($user)->for($company)->create([
                'status' => $status,
            ]);
        }
    }
}
